name: "Security Baseline Scanner"
description: "Easily scan a GitHub repository's against the Open Source Project Security Baseline"
author: "Revanite"
branding:
  icon: "search"
  color: "gray-dark"

inputs:
  REPO_OWNER:
    description: "Owner of the repo to scan, if not the same as the present repo's owner"
    required: false
    default: ""
  REPO_NAME:
    description: "Name of the repo to scan, if not the present repo"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.REPO_OWNER }}
    - ${{ inputs.REPO_NAME }}


